name: GitHub-Profile-3D-Contrib
on:
  schedule: [{cron: "0 18 * * *"}]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        with:
          USERNAME: tharcio09
          SETTING_JSON: conf/github-profile-3d-contrib.json # Opcional, usa padrão se não tiver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Push
        run: |
          git config user.name tharcio09
          git config user.email tharciosantos09@gmail.com
          git add -A .
          git commit -m "generated"
          git push
